services:
  app:
    image: golang:latest
    container_name: app1_app
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    networks:
      - app1

networks:
  app1: