services:
  app:
    image: golang:latest
    container_name: app1_app
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    networks:
      - app1
      - app_bridge

networks:
  app1:
    name: app1
  app_bridge:
    external: true