services:
  app:
    image: golang:latest
    container_name: app2_app
    ports:
      - "8080:80"
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    networks:
      - app2

networks:
  app2: